app_name="LocoLink"
app_token="App1Token"

[front_end]
views_path="./example/front-end/dist"
templates_path="./example/templates"
template_delimiter_start="<<"
template_delimiter_end=">>"

[web_server]
ip="127.0.0.1"
port=8000
stop_url="/stop-server"
restart_url="/restart-server"
auth_key="ticks24AuthKey"
mode="DEBUG"

[[app_databases]]
ip="127.0.0.1"
port=27017
database_name="locologic"
max_batch_size=1000

[auth_service]
ip="127.0.0.1"
port=7001
is_tcp=true
is_http=false

[log_config]
level="TRACE"
path="logs"
days=100